export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";

export const CHECK_REGISTER_USER_SUCCESS = "CHECK_REGISTER_USER_SUCCESS";
export const CHECK_REGISTER_USER_ERROR = "CHECK_REGISTER_USER_ERROR";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const CREATE_PREMISE_SUCCESS = "CREATE_PREMISE_SUCCESS";
export const CREATE_PREMISE_ERROR = "CREATE_TENANT_ERROR";

export const FETCH_PREMISES_SUCCESS = "FETCH_PREMISES_SUCCESS";
export const FETCH_PREMISES_ERROR = "FETCH_PREMISES_ERROR";

export const FETCH_RESIDENT_SUCCESS = "FETCH_RESIDENT_SUCCESS";
export const FETCH_RESIDENT_ERROR = "FETCH_RESIDENT_ERROR";

export const UPDATE_RESIDENT_SUCCESS = "UPDATE_RESIDENT_SUCCESS";
export const UPDATE_RESIDENT_ERROR = "UPDATE_RESIDENT_ERROR";

export const CREATE_PAYMENT_SUCCESS = 'CREATE_PAYMENT_SUCCESS'
export const CREATE_PAYMENT_ERROR = 'CREATE_PAYMENT_ERROR'

export const FETCH_PAYMENTS_SUCCESS = 'FETCH_PAYMENTS_SUCCESS'
export const FETCH_PAYMENTS_ERROR = 'FETCH_PAYMENTS_ERROR'

export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
